
package com.example.maven.jaxws.personclient.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "NoParamExeption", targetNamespace = "http://personservice.jaxws.maven.example.com/")
public class NoParamExeption
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonServiceFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoParamExeption(String message, PersonServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoParamExeption(String message, PersonServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.maven.jaxws.personclient.soap.PersonServiceFault
     */
    public PersonServiceFault getFaultInfo() {
        return faultInfo;
    }

}
