
package com.example.maven.jaxws.personservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.example.maven.jaxws.exept.PersonServiceFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1.7
 * 
 */
@XmlRootElement(name = "NoParamExeption", namespace = "http://personservice.jaxws.maven.example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoParamExeption", namespace = "http://personservice.jaxws.maven.example.com/", propOrder = {
    "faultInfo",
    "message",
    "suppressed"
})
public class NoParamExeptionBean {

    private PersonServiceFault faultInfo;
    private String message;
    private Throwable[] suppressed;

    /**
     * 
     * @return
     *     returns PersonServiceFault
     */
    public PersonServiceFault getFaultInfo() {
        return this.faultInfo;
    }

    /**
     * 
     * @param faultInfo
     *     the value for the faultInfo property
     */
    public void setFaultInfo(PersonServiceFault faultInfo) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 
     * @return
     *     returns Throwable[]
     */
    public Throwable[] getSuppressed() {
        return this.suppressed;
    }

    /**
     * 
     * @param suppressed
     *     the value for the suppressed property
     */
    public void setSuppressed(Throwable[] suppressed) {
        this.suppressed = suppressed;
    }

}
